### ISSUE TITLE
bitbake -ctestimage fails for qemuriscv64

### ISSUE THREAD

**Issue by kraj** [riscv/meta-riscv#112]
When running qemuriscv64 tests ptest fails to detect that system has booted, it open another backdoor serial to get that information but fails to communicate
add following in `local.conf`
```
IMAGE_CLASSES += "testimage testsdk"

TESTIMAGE_AUTO_qemuall = "1"
TEST_TARGET_IP_qemuall = "192.168.7.2"
TEST_QEMUBOOT_TIMEOUT = "50"
```
then run `bitbake core-image-base`

```
DEBUG: Not using kvm for runqemu
DEBUG: Created listening socket for qemu serial console on: 127.0.0.1:35303
DEBUG: Created listening socket for qemu serial console on: 127.0.0.1:36829
DEBUG: launchcmd=runqemu snapshot   nographic qemuriscv64 /mnt/a/yoe/build/tmp/deploy/images/qemuriscv64/core-image-base-qemuriscv64.ext4 tcpserial=36829 bootparams="console=tty1 console=ttyS0,115200n8 printk.time=1" qemuparams="-serial tcp:127.0.0.1:35303 -pidfile pidfile_14851"
DEBUG: runqemu started, pid is 14856
DEBUG: waiting at most 120 seconds for qemu pid (03/07/19 20:59:18)
DEBUG: qemu started in 0.5011918544769287 seconds - qemu procces pid is 14883 (03/07/19 20:59:18)
DEBUG: qemu cmdline used:
/mnt/a/yoe/build/tmp/work/x86_64-linux/qemu-helper-native/1.0-r1/recipe-sysroot-native/usr/bin/qemu-system-riscv64 -device virtio-net-device,netdev=net0,mac=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -drive id=disk0,file=/mnt/a/yoe/build/tmp/deploy/images/qemuriscv64/core-image-base-qemuriscv64.ext4,if=none,format=raw -device virtio-blk-device,drive=disk0 -show-cursor -monitor null -device loader,file=/mnt/a/yoe/build/tmp/deploy/images/qemuriscv64/Image,addr=0x80200000 -nographic -machine virt -m 512 -device virtio-serial-device -chardev socket,id=virtcon,port=36829,host=127.0.0.1 -device virtconsole,chardev=virtcon -serial tcp:127.0.0.1:35303 -pidfile pidfile_14851 -snapshot -kernel /mnt/a/yoe/build/tmp/deploy/images/qemuriscv64/fw_jump.elf -append root=/dev/vda rw highres=off  console=ttyS0 mem=512M ip=192.168.7.2::192.168.7.1:255.255.255.0 earlycon=sbi console=tty1 console=ttyS0,115200n8 printk.time=1
DEBUG: Target IP: 192.168.7.2
DEBUG: Server IP: 192.168.7.1
DEBUG: Starting logging thread
DEBUG: Starting thread event loop
DEBUG: Connection request received
DEBUG: Setting connection established event
DEBUG: Output from runqemu:
runqemu - INFO - Continuing with the following parameters:

runqemu - INFO - Setting up tap interface under sudo
runqemu - INFO - Network configuration: 192.168.7.2::192.168.7.1:255.255.255.0
runqemu - INFO - Running /mnt/a/yoe/build/tmp/work/x86_64-linux/qemu-helper-native/1.0-r1/recipe-sysroot-native/usr/bin/qemu-system-riscv64 -device virtio-net-device,netdev=net0,mac=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -drive id=disk0,file=/mnt/a/yoe/build/tmp/deploy/images/qemuriscv64/core-image-base-qemuriscv64.ext4,if=none,format=raw -device virtio-blk-device,drive=disk0 -show-cursor -monitor null -device loader,file=/mnt/a/yoe/build/tmp/deploy/images/qemuriscv64/Image,addr=0x80200000  -nographic -machine virt  -m 512 -device virtio-serial-device -chardev socket,id=virtcon,port=36829,host=127.0.0.1 -device virtconsole,chardev=virtcon  -serial tcp:127.0.0.1:35303 -pidfile pidfile_14851 -snapshot -kernel /mnt/a/yoe/build/tmp/deploy/images/qemuriscv64/fw_jump.elf -append 'root=/dev/vda rw highres=off  console=ttyS0 mem=512M ip=192.168.7.2::192.168.7.1:255.255.255.0 earlycon=sbi console=tty1 console=ttyS0,115200n8 printk.time=1'


DEBUG: Waiting at most 50 seconds for login banner (03/07/19 20:59:18)
DEBUG: Connection from 127.0.0.1:34768
DEBUG: Target didn't reach login banner in 50 seconds (03/07/19 21:00:08)
DEBUG: Last 25 lines of text:

[    6.531979] random: dbus-uuidgen: uninitialized urandom read (12 bytes read)
[    6.532810] random: dbus-uuidgen: uninitialized urandom read (8 bytes read)
Could not rename /var/lib/dbus/machine-id.MaM0qYMB to /var/lib/dbus/machine-id: Function not implemented

Starting system message bus: dbus.

Starting rpcbind daemon...done.

hwclock: Cannot access the Hardware Clock via any known method.

hwclock: Use the --verbose option to see the details of our search for an access method.

Starting syslogd/klogd: done

 * Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon

[A[74G[ ok ]

umount: /mnt/.psplash: not mounted.


Yoe Linux 2.6 qemuriscv64 ttyS0

qemuriscv64 login:
DEBUG: Check full boot log: /mnt/a/yoe/build/tmp/work/qemuriscv64-yoe-linux-musl/core-image-base/1.0-r0/testimage/qemu_boot_log.20190308045351
WARNING: Qemu ended unexpectedly, dump data from host is in /mnt/a/yoe/build/tmp/log/runtime-hostdump/201903072100_qemu
DEBUG: Stopping logging thread
DEBUG: Stop event received
DEBUG: Tearing down logging thread
DEBUG: Sending SIGTERM to runqemu
ERROR: testimage received SIGTERM, shutting down...
ERROR: core-image-base - FAILED - tests were interrupted during execution
ERROR:
DEBUG: Python function do_testimage finished
ERROR: Function failed: do_testimage

```

**Comment by kraj** [comment]
@alistair23 this the autotest issue that we need to solve soon

**Comment by alistair23** [comment]
Can you attach the full boot log?

**Comment by pino-kim** [comment]
Dear @kraj  @alistair23 

To fllowing your issue.
I under stand top comment attach below line at local.conf (yepp I mean auto.conf)
And just run `bitbake core-image-base` ?

>IMAGE_CLASSES += "testimage testsdk"
TESTIMAGE_AUTO_qemuall = "1"
TEST_TARGET_IP_qemuall = "192.168.7.2"
TEST_QEMUBOOT_TIMEOUT = "50"

**Comment by alistair23** [comment]
This works for me, at least it does detect the serial prompt

**Comment by alistair23** [comment]
This is the error I see (seems fair as I don't have GTK in the guest):

WARNING: core-image-base-1.0-r0 do_testimage: Not using kvm for runqemu
WARNING: core-image-base-1.0-r0 do_testimage: Created listening socket for qemu serial console on: 127.0.0.1:35975
WARNING: core-image-base-1.0-r0 do_testimage: Created listening socket for qemu serial console on: 127.0.0.1:45141
WARNING: core-image-base-1.0-r0 do_testimage: launchcmd=runqemu snapshot   qemuriscv64 /scratch/alistair/yocto/oe-master/build/tmp-glibc/deploy/images/qemuriscv64/core-image-base-qemuriscv64.ext4 tcpserial=45141 bootparams="console=tty1 console=ttyS0,115200n8 printk.time=1" qemuparams="-serial tcp:127.0.0.1:35975 -pidfile pidfile_8921"
WARNING: core-image-base-1.0-r0 do_testimage: runqemu started, pid is 8924
WARNING: core-image-base-1.0-r0 do_testimage: waiting at most 120 seconds for qemu pid (03/13/19 14:30:25)
WARNING: core-image-base-1.0-r0 do_testimage: qemu started in 0.5011353492736816 seconds - qemu procces pid is 8927 (03/13/19 14:30:25)
WARNING: core-image-base-1.0-r0 do_testimage: qemu cmdline used:
/scratch/alistair/yocto/oe-master/build/tmp-glibc/work/x86_64-linux/qemu-helper-native/1.0-r1/recipe-sysroot-native/usr/bin/qemu-system-riscv64 -device virtio-net-device,netdev=net0,mac=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -drive id=disk0,file=/scratch/alistair/yocto/oe-master/build/tmp-glibc/deploy/images/qemuriscv64/core-image-base-qemuriscv64.ext4,if=none,format=raw -device virtio-blk-device,drive=disk0 -show-cursor -monitor null -device loader,file=/scratch/alistair/yocto/oe-master/build/tmp-glibc/deploy/images/qemuriscv64/Image,addr=0x80200000 -machine virt -m 512 -device virtio-serial-device -chardev socket,id=virtcon,port=45141,host=127.0.0.1 -device virtconsole,chardev=virtcon -serial tcp:127.0.0.1:35975 -pidfile pidfile_8921 -snapshot -kernel /scratch/alistair/yocto/oe-master/build/tmp-glibc/deploy/images/qemuriscv64/fw_jump.elf -append root=/dev/vda rw highres=off  mem=512M ip=192.168.7.2::192.168.7.1:255.255.255.0 earlycon=sbi console=tty1 console=ttyS0,115200n8 printk.time=1 
WARNING: core-image-base-1.0-r0 do_testimage: Target IP: 192.168.7.2
WARNING: core-image-base-1.0-r0 do_testimage: Server IP: 192.168.7.1
WARNING: core-image-base-1.0-r0 do_testimage: Starting logging thread
WARNING: core-image-base-1.0-r0 do_testimage: Starting thread event loop
WARNING: core-image-base-1.0-r0 do_testimage: Connection request received
WARNING: core-image-base-1.0-r0 do_testimage: Setting connection established event
WARNING: core-image-base-1.0-r0 do_testimage: Output from runqemu:
runqemu - INFO - Continuing with the following parameters:

runqemu - INFO - Using preconfigured tap device tap0
runqemu - INFO - If this is not intended, touch /tmp/qemu-tap-locks/tap0.skip to make runqemu skip tap0.
runqemu - INFO - Network configuration: 192.168.7.2::192.168.7.1:255.255.255.0
runqemu - INFO - Running /scratch/alistair/yocto/oe-master/build/tmp-glibc/work/x86_64-linux/qemu-helper-native/1.0-r1/recipe-sysroot-native/usr/bin/qemu-system-riscv64 -device virtio-net-device,netdev=net0,mac=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -drive id=disk0,file=/scratch/alistair/yocto/oe-master/build/tmp-glibc/deploy/images/qemuriscv64/core-image-base-qemuriscv64.ext4,if=none,format=raw -device virtio-blk-device,drive=disk0 -show-cursor -monitor null -device loader,file=/scratch/alistair/yocto/oe-master/build/tmp-glibc/deploy/images/qemuriscv64/Image,addr=0x80200000  -machine virt  -m 512 -device virtio-serial-device -chardev socket,id=virtcon,port=45141,host=127.0.0.1 -device virtconsole,chardev=virtcon  -serial tcp:127.0.0.1:35975 -pidfile pidfile_8921 -snapshot -kernel /scratch/alistair/yocto/oe-master/build/tmp-glibc/deploy/images/qemuriscv64/fw_jump.elf -append 'root=/dev/vda rw highres=off  mem=512M ip=192.168.7.2::192.168.7.1:255.255.255.0 earlycon=sbi console=tty1 console=ttyS0,115200n8 printk.time=1'


WARNING: core-image-base-1.0-r0 do_testimage: Waiting at most 50 seconds for login banner (03/13/19 14:30:25)
WARNING: core-image-base-1.0-r0 do_testimage: Connection from 127.0.0.1:54668
WARNING: core-image-base-1.0-r0 do_testimage: Reached login banner in 29.547985553741455 seconds (03/13/19 14:30:55)
WARNING: core-image-base-1.0-r0 do_testimage: Logged as root in serial console
Not starting HTTPService for directory tmp-glibc/deploy/deb/all which doesn't exist
Test requires apt to be installed
Stopped HTTPService on 192.168.7.1:0
Traceback (most recent call last):
  File "/scratch/alistair/yocto/oe-master/meta/lib/oeqa/core/decorator/__init__.py", line 32, in wrapped_f
    return func(*args, **kwargs)
  File "/scratch/alistair/yocto/oe-master/meta/lib/oeqa/core/decorator/__init__.py", line 32, in wrapped_f
    return func(*args, **kwargs)
  File "/scratch/alistair/yocto/oe-master/meta/lib/oeqa/core/decorator/__init__.py", line 32, in wrapped_f
    return func(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/scratch/alistair/yocto/oe-master/meta/lib/oeqa/runtime/cases/buildgalculator.py", line 28, in test_galculator
    self.project.run_configure()
  File "/scratch/alistair/yocto/oe-master/meta/lib/oeqa/utils/buildproject.py", line 49, in run_configure
    return self._run('cd %s; gnu-configize; %s ./configure %s' % (self.targetdir, extra_cmds, configure_args))
  File "/scratch/alistair/yocto/oe-master/meta/lib/oeqa/runtime/utils/targetbuildproject.py", line 40, in _run
    raise Exception(msg)
Exception: Command cd ~/buildtest/galculator-2.1.4; gnu-configize;  ./configure  failed with exit code 1: checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/home/root/buildtest/galculator-2.1.4/missing: Unknown `--is-lightweight' option
Try `/home/root/buildtest/galculator-2.1.4/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking whether NLS is requested... yes
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.28.1
checking for library containing strerror... none required
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking build system type... riscv64-unknown-linux-gnu
checking host system type... riscv64-unknown-linux-gnu
checking for cos in -lm... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GTK... no
configure: error: Package requirements (gtk+-3.0) were not met:

No package 'gtk+-3.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTK_CFLAGS
and GTK_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

Test requires connman to be installed
Test case connman.ConnmanTest.test_connmand_running depends on connman.ConnmanTest.test_connmand_help but it didn't pass/run.
Test requires dnf to be installed
Test case dnf.DnfBasicTest.test_dnf_history depends on dnf.DnfBasicTest.test_dnf_help but it didn't pass/run.
Test case dnf.DnfBasicTest.test_dnf_info depends on dnf.DnfBasicTest.test_dnf_help but it didn't pass/run.
Test case dnf.DnfBasicTest.test_dnf_search depends on dnf.DnfBasicTest.test_dnf_help but it didn't pass/run.
Test case dnf.DnfBasicTest.test_dnf_version depends on dnf.DnfBasicTest.test_dnf_help but it didn't pass/run.
Not starting HTTPService for directory /scratch/alistair/yocto/oe-master/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-base/1.0-r0/oe-testimage-repo which doesn't exist
Test case dnf.DnfRepoTest.test_dnf_makecache depends on dnf.DnfBasicTest.test_dnf_help but it didn't pass/run.
Test case dnf.DnfRepoTest.test_dnf_exclude depends on dnf.DnfRepoTest.test_dnf_makecache but it didn't pass/run.
Test case dnf.DnfRepoTest.test_dnf_install depends on dnf.DnfRepoTest.test_dnf_makecache but it didn't pass/run.
Test case dnf.DnfRepoTest.test_dnf_install_dependency depends on dnf.DnfRepoTest.test_dnf_install but it didn't pass/run.
Test case dnf.DnfRepoTest.test_dnf_install_from_disk depends on dnf.DnfRepoTest.test_dnf_install_dependency but it didn't pass/run.
Test case dnf.DnfRepoTest.test_dnf_install_from_http depends on dnf.DnfRepoTest.test_dnf_install_from_disk but it didn't pass/run.
Test case dnf.DnfRepoTest.test_dnf_installroot depends on dnf.DnfRepoTest.test_dnf_makecache but it didn't pass/run.
Test case dnf.DnfRepoTest.test_dnf_reinstall depends on dnf.DnfRepoTest.test_dnf_install but it didn't pass/run.
Test case dnf.DnfRepoTest.test_dnf_repoinfo depends on dnf.DnfRepoTest.test_dnf_makecache but it didn't pass/run.
Stopped HTTPService on 192.168.7.1:0
Test requires python3-pygobject to be installed
Test requires kernel-devsrc to be installed
Test requires logrotate to be installed
Test case logrotate.LogrotateTest.test_2_logrotate depends on logrotate.LogrotateTest.test_1_logrotate_setup but it didn't pass/run.
Not appropiate for systemd image
Started HTTPService on 192.168.7.1:34301
Stopped HTTPService on 192.168.7.1:34301
Test requires pam to be in DISTRO_FEATURES
Test requires ptest-runner to be installed
No /var/lib/rpm on target
Test case rpm.RpmInstallRemoveTest.test_rpm_install depends on rpm.RpmBasicTest.test_rpm_query but it didn't pass/run.
Test case rpm.RpmInstallRemoveTest.test_rpm_remove depends on rpm.RpmInstallRemoveTest.test_rpm_install but it didn't pass/run.
Test case rpm.RpmInstallRemoveTest.test_check_rpm_install_removal_log_file_size depends on rpm.RpmInstallRemoveTest.test_rpm_remove but it didn't pass/run.
Test case rpm.RpmInstallRemoveTest.test_rpm_query_nonroot depends on rpm.RpmBasicTest.test_rpm_query but it didn't pass/run.
Test requires systemtap to be installed
Startup finished in 3.038s (kernel) + 25.567s (userspace) = 28.606s.
Test requires xserver-nodm-init to be installed
WARNING: core-image-base-1.0-r0 do_testimage: Stopping logging thread
WARNING: core-image-base-1.0-r0 do_testimage: Stop event received
WARNING: core-image-base-1.0-r0 do_testimage: Tearing down logging thread
WARNING: core-image-base-1.0-r0 do_testimage: Sending SIGTERM to runqemu
RESULTS:
RESULTS - buildcpio.BuildCpioTest.test_cpio - Testcase 205: PASSED (567.32s)
RESULTS - buildlzip.BuildLzipTest.test_lzip - Testcase 206: PASSED (106.93s)
RESULTS - date.DateTest.test_date - Testcase 211: PASSED (2.96s)
RESULTS - df.DfTest.test_df - Testcase 234: PASSED (0.56s)
RESULTS - gcc.GccCompileTest.test_gcc_compile - Testcase 203: PASSED (3.50s)
RESULTS - gcc.GccCompileTest.test_gpp2_compile - Testcase 1142: PASSED (3.70s)
RESULTS - gcc.GccCompileTest.test_gpp_compile - Testcase 200: PASSED (4.40s)
RESULTS - gcc.GccCompileTest.test_make - Testcase 204: PASSED (2.71s)
RESULTS - ldd.LddTest.test_ldd - Testcase 962: PASSED (1.41s)
RESULTS - oe_syslog.SyslogTest.test_syslog_running - Testcase 201: PASSED (0.47s)
RESULTS - oe_syslog.SyslogTestConfig.test_syslog_logger - Testcase 1149: PASSED (0.75s)
RESULTS - oe_syslog.SyslogTestConfig.test_syslog_restart - Testcase 1150: PASSED (0.54s)
RESULTS - opkg.OpkgRepoTest.test_opkg_install_from_repo - Testcase -1: PASSED (9.15s)
RESULTS - parselogs.ParseLogsTest.test_parselogs - Testcase 1059: PASSED (5.37s)
RESULTS - perl.PerlTest.test_perl_works - Testcase 208: PASSED (0.41s)
RESULTS - ping.PingTest.test_ping - Testcase 964: PASSED (0.27s)
RESULTS - python.PythonTest.test_python3 - Testcase 965: PASSED (0.85s)
RESULTS - rpm.RpmBasicTest.test_rpm_help - Testcase 960: PASSED (0.49s)
RESULTS - scp.ScpTest.test_scp_file - Testcase 220: PASSED (2.52s)
RESULTS - ssh.SSHTest.test_ssh - Testcase 224: PASSED (2.05s)
RESULTS - systemd.SystemdBasicTests.test_systemd_basic - Testcase -1: PASSED (0.39s)
RESULTS - systemd.SystemdBasicTests.test_systemd_failed - Testcase 550: PASSED (0.81s)
RESULTS - systemd.SystemdBasicTests.test_systemd_list - Testcase 551: PASSED (13.50s)
RESULTS - systemd.SystemdJournalTests.test_systemd_boot_time - Testcase -1: PASSED (0.42s)
RESULTS - systemd.SystemdJournalTests.test_systemd_journal - Testcase -1: PASSED (0.49s)
RESULTS - systemd.SystemdServiceTests.test_systemd_disable_enable - Testcase 696: PASSED (6.87s)
RESULTS - systemd.SystemdServiceTests.test_systemd_status - Testcase -1: PASSED (0.47s)
RESULTS - systemd.SystemdServiceTests.test_systemd_stop_start - Testcase 695: PASSED (2.10s)
RESULTS - apt.AptRepoTest.test_apt_install_from_repo - Testcase -1: SKIPPED (0.00s)
RESULTS - connman.ConnmanTest.test_connmand_help - Testcase 961: SKIPPED (0.00s)
RESULTS - connman.ConnmanTest.test_connmand_running - Testcase 221: SKIPPED (0.00s)
RESULTS - dnf.DnfBasicTest.test_dnf_help - Testcase 1735: SKIPPED (0.00s)
RESULTS - dnf.DnfBasicTest.test_dnf_history - Testcase 1736: SKIPPED (0.00s)
RESULTS - dnf.DnfBasicTest.test_dnf_info - Testcase 1737: SKIPPED (0.00s)
RESULTS - dnf.DnfBasicTest.test_dnf_search - Testcase 1738: SKIPPED (0.00s)
RESULTS - dnf.DnfBasicTest.test_dnf_version - Testcase 1739: SKIPPED (0.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_exclude - Testcase 1772: SKIPPED (0.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_install - Testcase 1740: SKIPPED (0.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_install_dependency - Testcase 1741: SKIPPED (0.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_install_from_disk - Testcase 1742: SKIPPED (0.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_install_from_http - Testcase 1743: SKIPPED (0.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_installroot - Testcase 1771: SKIPPED (0.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_makecache - Testcase 1744: SKIPPED (0.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_reinstall - Testcase 1745: SKIPPED (0.00s)
RESULTS - dnf.DnfRepoTest.test_dnf_repoinfo - Testcase 1746: SKIPPED (0.00s)
RESULTS - gi.GObjectIntrospectionTest.test_python - Testcase -1: SKIPPED (0.00s)
RESULTS - kernelmodule.KernelModuleTest.test_kernel_module - Testcase 1541: SKIPPED (0.00s)
RESULTS - logrotate.LogrotateTest.test_1_logrotate_setup - Testcase 1544: SKIPPED (0.00s)
RESULTS - logrotate.LogrotateTest.test_2_logrotate - Testcase 1542: SKIPPED (0.00s)
RESULTS - oe_syslog.SyslogTestConfig.test_syslog_startup_config - Testcase 202: SKIPPED (0.00s)
RESULTS - pam.PamBasicTest.test_pam - Testcase 1543: SKIPPED (0.00s)
RESULTS - ptest.PtestRunnerTest.test_ptestrunner - Testcase 1600: SKIPPED (0.00s)
RESULTS - rpm.RpmBasicTest.test_rpm_query - Testcase 191: SKIPPED (0.36s)
RESULTS - rpm.RpmInstallRemoveTest.test_check_rpm_install_removal_log_file_size - Testcase 195: SKIPPED (0.00s)
RESULTS - rpm.RpmInstallRemoveTest.test_rpm_install - Testcase 192: SKIPPED (0.00s)
RESULTS - rpm.RpmInstallRemoveTest.test_rpm_query_nonroot - Testcase 1096: SKIPPED (0.00s)
RESULTS - rpm.RpmInstallRemoveTest.test_rpm_remove - Testcase 194: SKIPPED (0.00s)
RESULTS - stap.StapTest.test_stap - Testcase 1652: SKIPPED (0.00s)
RESULTS - xorg.XorgTest.test_xorg_running - Testcase 1151: SKIPPED (0.00s)
RESULTS - buildgalculator.GalculatorTest.test_galculator - Testcase 1526: ERROR (30.95s)
SUMMARY:
core-image-base () - Ran 60 tests in 775.999s
core-image-base - FAIL - Required tests failed (successes=28, skipped=31, failures=0, errors=1)
ERROR: core-image-base-1.0-r0 do_testimage: core-image-base - FAILED - check the task log and the ssh log
ERROR: core-image-base-1.0-r0 do_testimage: 
ERROR: core-image-base-1.0-r0 do_testimage: Function failed: do_testimage
ERROR: Logfile of failure stored in: /scratch/alistair/yocto/oe-master/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-base/1.0-r0/temp/log.do_testimage.8921
ERROR: Task (/scratch/alistair/yocto/oe-master/meta/recipes-core/images/core-image-base.bb:do_testimage) failed with exit code '1'
NOTE: Tasks Summary: Attempted 4019 tasks of which 3822 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /scratch/alistair/yocto/oe-master/meta/recipes-core/images/core-image-base.bb:do_testimage
Summary: There were 25 WARNING messages shown.
Summary: There were 3 ERROR messages shown, returning a non-zero exit code.

**Comment by alistair23** [comment]
I have merged some improvements. Let me know if you still see this issue. It now works for me with and without the meta-riscv layer (with some extra patches)

**Comment by kraj** [comment]
With the latest patchset, this has started to work, there are failures but thats a different issue
