### ISSUE TITLE
Support golang

### ISSUE THREAD

**Issue by tuanha-viosoft** [riscv/meta-riscv#114]
Can you consider to support golang for riscv?

**Comment by pino-kim** [comment]
@tuanha-viosoft 
I'm interesting your issue.
By the way. current upstreaming go only support riscv64 versoion 1.11?

**Comment by tuanha-viosoft** [comment]
@pino-kim The upstream golang doesn’t support riscv. I found a porting golang for riscv here
https://github.com/riscv/riscv-go

**Comment by pino-kim** [comment]
@tuanha-viosoft 
Thanks to reply. yepp you right.
I ask  some Question to golang. 
https://github.com/golang/go/issues/30697

**Comment by kraj** [comment]
I am certainly open to have bbappend to point to risvc fork.

**Comment by alistair23** [comment]
Just an update, it looks like RISC-V support is going into go-lang: https://github.com/golang/go/issues/27532

**Comment by 4a6f656c** [comment]
A version of Go that supports RISC-V (riscv64) can be found at https://github.com/4a6f656c/riscv-go - this repo contains branches with Go 1.13 and Go tip (along with older Go releases). I'm in the process of getting this merged upstream, which will hopefully mean it becomes available in the Go 1.14 release.
