### ISSUE TITLE
Install vim and bash to riscv 32bit machine

### ISSUE THREAD

**Issue by geonheec** [riscv/meta-riscv#197]
How can I install vim and bash to riscv 32bit machine?

In current state, when I tried` ls `command, directories, executables, and regular files are the same color.
And when I open the *.c file, all the code is white color.
So I want to install vim and color my code in riscv 32bit machine.

**Comment by kraj** [comment]
in local.conf add `IMAGE_INSTALL += "vim bash"`

**Comment by kraj** [comment]
closing please reopen if needed
