### ISSUE TITLE
qemuriscv32 kernel panic when tools-sdk installed

### ISSUE THREAD

**Issue by geonheec** [riscv/meta-riscv#199]
Hi, I tried to make riscv32 virtual machine and it was successful.

But when I tried to install tools-sdk additionally for gcc, the kernel panic is occurred and the virtual machine stop booting.

I add the following line in local.conf
`EXTRA_IMAGE_FEATURES_append = " tools-debug tools-sdk dbg-pkgs ssh-server-openssh"`

`MACHINE=qemuriscv32 bitbake core-image-full-cmdline` works well and seems to be no problem.
But `MACHINE=qemuriscv32 runqemu nographic slirp` does not work. It hang with kernel panic during boot.

```
[    4.281021] Run /sbin/init as init process
FATAL: kernel too old
[    4.331408] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00
[    4.331792] CPU: 0 PID: 1 Comm: init Not tainted 5.2.28-yocto-standard #1
[    4.332170] Call Trace:
[    4.332411] [<c0052a9e>] walk_stackframe+0x0/0xa6
[    4.332637] [<c0052c74>] show_stack+0x28/0x32
[    4.332841] [<c0664372>] dump_stack+0x6e/0x8a
[    4.333021] [<c0057e6c>] panic+0xee/0x26e
[    4.333195] [<c005b0b8>] do_exit+0x784/0x7ea
[    4.333410] [<c005b172>] do_group_exit+0x2a/0x82
[    4.333599] [<c005b1dc>] __wake_up_parent+0x0/0x22
[    4.333779] [<c00515e6>] ret_from_syscall+0x0/0xe
[    4.334288] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x00007f00 ]---
```

Is there another way to add gcc in qemuriscv32 vm?

**Comment by geonheec** [comment]
ah, let me correct what I said above. 
This error seems to occur whether or not tools-sdk is added.

**Comment by kraj** [comment]
instead of adding all tools-sdk Can you just try to add
```
IMAGE_INSTALL_append = " cpp"
```
and see if this fails too ?

**Comment by kraj** [comment]
ah I see the real issue seems to be 
```
FATAL: kernel too old
```

Its a config setting that should match glibc's expectations

**Comment by kraj** [comment]
@alistair23  in your fork of glibc for rv32 you bumped the minimum kernel needed for rv32 to 5.2  [1] but linux-yocto is still at 5.2, thats why we see the boot failure above. should we use linux-mainline_5.4.bb in interim ?

[1] https://github.com/alistair23/glibc/commit/d0c0df6f2d5b7ab1b62bbec7dfe20f4732f938d1

**Comment by alistair23** [comment]
Sorry I have other changes. You need the 5.4 kernel. You can use linux-mainline instead of linux-yocto which should worm
