### ISSUE TITLE
Index-pack error

### ISSUE THREAD

**Issue by kirana1996** [riscv/meta-riscv#229]
hi,
when i am cloning riscv-gnu-toolchain (git clone git clone --recursive https://github.com/riscv/riscv-gnu-toolchain) getting fallowing error.
 $git clone --recursive https://github.com/riscv/riscv-gnu-toolchain
Cloning into 'riscv-gnu-toolchain'...
remote: Enumerating objects: 30, done.
remote: Counting objects: 100% (30/30), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 7731 (delta 10), reused 18 (delta 5), pack-reused 7701
Receiving objects: 100% (7731/7731), 4.74 MiB | 1.46 MiB/s, done.
Resolving deltas: 100% (3912/3912), done.
Submodule 'qemu' (https://git.qemu.org/git/qemu.git) registered for path 'qemu'
Submodule 'riscv-binutils' (https://github.com/riscv/riscv-binutils-gdb.git) registered for path 'riscv-binutils'
Submodule 'riscv-dejagnu' (https://github.com/riscv/riscv-dejagnu.git) registered for path 'riscv-dejagnu'
Submodule 'riscv-gcc' (https://github.com/riscv/riscv-gcc.git) registered for path 'riscv-gcc'
Submodule 'riscv-gdb' (https://github.com/riscv/riscv-binutils-gdb.git) registered for path 'riscv-gdb'
Submodule 'riscv-glibc' (https://github.com/riscv/riscv-glibc.git) registered for path 'riscv-glibc'
Submodule 'riscv-newlib' (https://github.com/riscv/riscv-newlib.git) registered for path 'riscv-newlib'
Cloning into '/home/root/riscv-gnu-toolchain/qemu'...
remote: Counting objects: 501059, done.        
remote: Compressing objects: 100% (92200/92200), done.        
remote: Total 501059 (delta 412170), reused 495480 (delta 407514)        
Receiving objects: 100% (501059/501059), 176.60 MiB | 609.00 KiB/s, done.
Resolving deltas: 100% (412170/412170), done.
Cloning into '/home/root/riscv-gnu-toolchain/riscv-binutils'...
remote: Enumerating objects: 53, done.        
remote: Counting objects: 100% (53/53), done.        
remote: Compressing objects: 100% (44/44), done.        
remote: Total 881261 (delta 26), reused 24 (delta 9), pack-reused 881208        
Receiving objects: 100% (881261/881261), 335.08 MiB | 2.02 MiB/s, done.
Resolving deltas: 100% (731781/731781), done.
Cloning into '/home/root/riscv-gnu-toolchain/riscv-dejagnu'...
remote: Enumerating objects: 5208, done.        
remote: Total 5208 (delta 0), reused 0 (delta 0), pack-reused 5208        
Receiving objects: 100% (5208/5208), 3.10 MiB | 1.42 MiB/s, done.
Resolving deltas: 100% (3957/3957), done.
Cloning into '/home/root/riscv-gnu-toolchain/riscv-gcc'...
remote: Enumerating objects: 81, done.        
remote: Counting objects: 100% (81/81), done.        
remote: Compressing objects: 100% (35/35), done.        
remote: Total 2451850 (delta 48), reused 62 (delta 41), pack-reused 2451769        
Receiving objects: 100% (2451850/2451850), 1.20 GiB | 2.38 MiB/s, done.
[ 4556.613474] git invoked oom-killer: gfp_mask=0x100cca(GFP_HIGHUSER_MOVABLE), order=0, oom_score_adj=0
[ 4556.616326] CPU: 0 PID: 1408 Comm: git Not tainted 5.5.6 #1
[ 4556.616950] Call Trace:
[ 4556.617897] [<ffffffe00003bf0a>] walk_stackframe+0x0/0xa4
[ 4556.618353] [<ffffffe00003c0f0>] show_stack+0x2a/0x34
[ 4556.618640] [<ffffffe00063673a>] dump_stack+0x6a/0x84
[ 4556.618960] [<ffffffe0000df2c8>] dump_header+0x48/0x258
[ 4556.619238] [<ffffffe0000dea8c>] oom_kill_process+0x330/0x332
[ 4556.619583] [<ffffffe0000def30>] out_of_memory+0xaa/0x3a0
[ 4556.619867] [<ffffffe000113f6a>] __alloc_pages_slowpath+0x746/0x82c
[ 4556.620188] [<ffffffe0001141b2>] __alloc_pages_nodemask+0x162/0x186
[ 4556.620496] [<ffffffe000100be2>] __handle_mm_fault+0x3be/0x9bc
[ 4556.620800] [<ffffffe00010123e>] handle_mm_fault+0x5e/0xa2
[ 4556.621084] [<ffffffe00003d866>] do_page_fault+0xb8/0x2da
[ 4556.621361] [<ffffffe00003aca8>] ret_from_exception+0x0/0xc
[ 4556.621848] Mem-Info:
[ 4556.622204] active_anon:94807 inactive_anon:4410 isolated_anon:0
[ 4556.622204]  active_file:450 inactive_file:462 isolated_file:0
[ 4556.622204]  unevictable:0 dirty:0 writeback:0 unstable:0
[ 4556.622204]  slab_reclaimable:1734 slab_unreclaimable:2268
[ 4556.622204]  mapped:2582 shmem:4435 pagetables:392 bounce:0
[ 4556.622204]  free:2037 free_pcp:156 free_cma:0
[ 4556.623971] Node 0 active_anon:379228kB inactive_anon:17640kB active_file:1800kB inactive_file:1848kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:10328kB dirty:0kB writeback:0kB shmem:17740kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[ 4556.625043] DMA32 free:8148kB min:8600kB low:9260kB high:9920kB reserved_highatomic:4096KB active_anon:379228kB inactive_anon:17640kB active_file:1800kB inactive_file:1848kB unevictable:0kB writepending:0kB present:522240kB managed:439188kB mlocked:0kB kernel_stack:624kB pagetables:1568kB bounce:0kB free_pcp:624kB local_pcp:624kB free_cma:0kB
[ 4556.626348] lowmem_reserve[]: 0 0 0
[ 4556.626713] DMA32: 148*4kB (UMH) 184*8kB (UMEH) 159*16kB (UMEH) 59*32kB (UEH) 16*64kB (UEH) 3*128kB (H) 1*256kB (H) 0*512kB 0*1024kB 0*2048kB 0*4096kB = 8160kB
[ 4556.627724] 5355 total pagecache pages
[ 4556.628016] 0 pages in swap cache
[ 4556.628204] Swap cache stats: add 0, delete 0, find 0/0
[ 4556.628524] Free swap  = 0kB
[ 4556.628719] Total swap = 0kB
[ 4556.628966] 130560 pages RAM
[ 4556.629150] 0 pages HighMem/MovableOnly
[ 4556.629382] 20763 pages reserved
[ 4556.629651] Tasks state (memory values in pages):
[ 4556.629920] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[ 4556.630486] [     63]     0    63      605       35    24576        0             0 rngd
[ 4556.630925] [     64]   995    64      626       55    24576        0             0 rpcbind
[ 4556.631375] [     65]     0    65     8006     2054    57344        0          -250 systemd-journal
[ 4556.631999] [     79]     0    79     2910      279    28672        0         -1000 systemd-udevd
[ 4556.632397] [     87]   990    87    19773       84    40960        0             0 systemd-timesyn
[ 4556.632777] [     98]     0    98      625       18    24576        0             0 klogd
[ 4556.633108] [     99]     0    99      625       18    28672        0             0 syslogd
[ 4556.633445] [    100]   997   100      792      133    28672        0          -900 dbus-daemon
[ 4556.633870] [    102]     0   102     7032       47    32768        0             0 agetty
[ 4556.634280] [    105]     0   105      381       48    20480        0             0 agetty
[ 4556.634693] [    106]     0   106      908      406    28672        0             0 sh
[ 4556.635131] [    119]     0   119     1311       99    32768        0             0 systemd-logind
[ 4556.635891] [    120]   992   120     1420      106    28672        0             0 systemd-network
[ 4556.636379] [    121]     0   121     2054      174    32768        0             0 connmand
[ 4556.636790] [    123]   998   123      802       84    24576        0             0 avahi-daemon
[ 4556.637224] [    126]   994   126      583      182    28672        0             0 rpc.statd
[ 4556.637696] [    127]     0   127     4835     1532    53248        0             0 snmpd
[ 4556.638129] [    128]     0   128     2132      489    40960        0             0 snmptrapd
[ 4556.638580] [    131]     0   131    34217     1327   114688        0             0 containerd
[ 4556.639030] [    132]   998   132      769       60    24576        0             0 avahi-daemon
[ 4556.639470] [    135] 65534   135      424       31    24576        0             0 dnsmasq
[ 4556.639953] [    141]     0   141     1997      113    36864        0             0 wpa_supplicant
[ 4556.640329] [    871]     0   871     3762     1181    45056        0             0 git
[ 4556.640683] [    878]     0   878      952       22    28672        0             0 git
[ 4556.641016] [    879]     0   879      771      261    24576        0             0 git-submodule
[ 4556.641387] [    907]     0   907      771      241    24576        0             0 git-submodule
[ 4556.641852] [    908]     0   908      771      224    24576        0             0 git-submodule
[ 4556.642324] [    909]     0   909     1244       85    36864        0             0 git
[ 4556.642737] [   1398]     0  1398      952       22    28672        0             0 git
[ 4556.643169] [   1399]     0  1399      985      129    28672        0             0 git
[ 4556.643807] [   1400]     0  1400    21328      973    53248        0             0 git-remote-http
[ 4556.644316] [   1402]     0  1402    19417       78    28672        0             0 git
[ 4556.644754] [   1408]     0  1408    89327    86244   724992        0             0 git
[ 4556.645173] [   1751]     0  1751      624       31    24576        0             0 xinit
[ 4556.645586] [   1754]     0  1754     2636      343    36864        0             0 Xorg
[ 4556.646059] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),task=git,pid=1408,uid=0
[ 4556.646716] Out of memory: Killed process 1408 (git) total-vm:357308kB, anon-rss:344100kB, file-rss:876kB, shmem-rss:0kB, UID:0 pgtables:708kB oom_score_adj:0
[ 4556.847993] oom_reaper: reaped process 1408 (git), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
error: index-pack died of signal 9
fatal: index-pack failed
fatal: clone of 'https://github.com/riscv/riscv-gcc.git' into submodule path '/home/root/riscv-gnu-toolchain/riscv-gcc' failed
Failed to clone 'riscv-gcc'. Retry scheduled

please help me to fix them

Thanks,

**Comment by kraj** [comment]
@kirana1996 this is architecture layer for supporting OE and Yocto project, what you are building is an external toolchain so perhaps its better to open a GitHub issue with https://github.com/riscv/riscv-gnu-toolchain/issues, OE also builds a toolchain for RISC-V internally using upstream GCC and other components if you are interested you can use this approach too.
