### ISSUE TITLE
[Question] MACHINE=freedom-u540 bitbake core-image-wayland can't build

### ISSUE THREAD

**Issue by pino-kim** [riscv/meta-riscv#232]
**Description**
I make this issue(**question**) about MACHINE=freedom-u540 bitbake **core-image-wayland**
I can't build MACHINE=freedom-u540 bitbake **core-image-wayland** 
Should I add more meta-layer for build **core-image-wayland**  or read more doc to follow? 

**Steps to reproduce the issue:**
1. follow the Setup Build Environment on the README.md.
2. run $MACHINE=freedom-u540 bitbake **core-image-wayland**

**Describe the results you received:**
build starting.

**Describe the results you expected:**
can not found **core-image-wayland**.

**Additional information you deem important (e.g. issue happens only occasionally):** 

**Additional details (revisions used, host distro, etc.):**
Build Host: ubuntu 18.04

**Comment by kraj** [comment]
@pino-kim there is no pre-existing `core-image-wayland` but there is a similar reference image called `core-image-weston` please use that as target

**Comment by pino-kim** [comment]
@kraj 
Thanks for your reply. 
I can't find core-image-wayland too.

So, follow your guild.
$MACHINE=freedom-u540 bitbake core-image-wayland
to
$MACHINE=freedom-u540 bitbake core-image-weston

Thanks.

**Comment by pino-kim** [comment]
Thanks @kraj 
I can build **core-image-weston** image.
Would you check up PR #233 ?

Close this issue.
