### ISSUE TITLE
What's the password of default images

### ISSUE THREAD

**Issue by drcut** [riscv/meta-riscv#260]
**Description**

Hi, I just following the steps in README for using riscv64qemu, and now I can succeed build the Image, however, I do not find the password while executing 
```bash
 MACHINE=qemuriscv64 runqemu nographic
```
Would you please give me suggestions? Thanks

Here is the log:
```
runqemu - INFO - Running MACHINE=qemuriscv64 bitbake -e ...
runqemu - INFO - Continuing with the following parameters:
KERNEL: [/home/hanruobing/riscv-yocto/build/tmp-glibc/deploy/images/qemuriscv64/Image--5.8.18+git0+b976de4f41_3c5d210805-r0-qemuriscv64-20210105034301.bin]
BIOS: [/home/hanruobing/riscv-yocto/build/tmp-glibc/deploy/images/qemuriscv64/fw_jump.elf]
MACHINE: [qemuriscv64]
FSTYPE: [ext4]
ROOTFS: [/home/hanruobing/riscv-yocto/build/tmp-glibc/deploy/images/qemuriscv64/core-image-full-cmdline-qemuriscv64-20210105034301.rootfs.ext4]
CONFFILE: [/home/hanruobing/riscv-yocto/build/tmp-glibc/deploy/images/qemuriscv64/core-image-full-cmdline-qemuriscv64-20210105034301.qemuboot.conf]

runqemu - INFO - Setting up tap interface under sudo

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password:

```

**Comment by kraj** [comment]
make sure you have `debug-tweaks` in `IMAGE_FEATURES` and then it will have no password for `root` user just add it via conf/local.conf 

`IMAGE_FEATURES_append = " debug-tweaks"`

**Comment by drcut** [comment]
> make sure you have `debug-tweaks` in `IMAGE_FEATURES` and then it will have no password for `root` user just add it via conf/local.conf
> 
> `IMAGE_FEATURES_append = " debug-tweaks"`

Thanks for your suggestion! Now I just though that password is not for QEMU image, but for host.
```bash
robinhan@rover:~/riscv-yocto$ MACHINE=qemuriscv64 runqemu nographic
runqemu - INFO - Running MACHINE=qemuriscv64 bitbake -e ...
runqemu - INFO - Continuing with the following parameters:
KERNEL: [/tmp/Yocto-glibc/deploy/images/qemuriscv64/Image--5.10.2+git0+6b12385f7d_0c61b00f3d-r0-qemuriscv64-20210106042421.bin]
BIOS: [/tmp/Yocto-glibc/deploy/images/qemuriscv64/fw_jump.elf]
MACHINE: [qemuriscv64]
FSTYPE: [ext4]
ROOTFS: [/tmp/Yocto-glibc/deploy/images/qemuriscv64/core-image-full-cmdline-qemuriscv64-20210106042421.rootfs.ext4]
CONFFILE: [/tmp/Yocto-glibc/deploy/images/qemuriscv64/core-image-full-cmdline-qemuriscv64-20210106042421.qemuboot.conf]

runqemu - INFO - Setting up tap interface under sudo
sudo: unable to execute /home/robinhan/riscv-yocto/openembedded-core/scripts/runqemu-ifup: Permission denied
runqemu - ERROR - Setting up tap device failed:
Command '('sudo', '/home/robinhan/riscv-yocto/openembedded-core/scripts/runqemu-ifup', '1388350517', '7001', '/tmp/Yocto-glibc/work/x86_64-linux/qemu-helper-native/1.0-r1/recipe-sysroot-native/usr/bin/')' returned non-zero exit status 1.
Run runqemu-gen-tapdevs to manually create one.
runqemu - INFO - Cleaning up
```

Seems weird why even using sudo to execute runqemu-ifup also raise Permission denied :(

**Comment by alistair23** [comment]
When starting QEMU you can specify `slirip` to avoid settign up the TAP interface.

`$ runqemu slirp`

**Comment by drcut** [comment]
> When starting QEMU you can specify `slirip` to avoid settign up the TAP interface.
> 
> `$ runqemu slirp`

Great! It works. But why it failed? I think it does use root to execute the runqemu-ifup script?

**Comment by alistair23** [comment]
You need root to setup a TAP interface: https://wiki.qemu.org/Documentation/Networking#Tap

A TAP interface is more powerful and can be used to expose QEMU guests to public IPs. If you just need internet though slirp networking is more then enough, just remember that PING won't work.
