### ISSUE TITLE
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with gatesgarth)

### ISSUE THREAD

**Issue by Kottoz** [riscv/meta-riscv#276]
i'm trying to build project using Yocto, and this error faced me, how can I solve it ?

```
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/kotoz/sys_updr_exp_0-0/rpi64/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 16167 at 2021-03-25 11:44:48.669873 ---
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with gatesgarth)
```

i have looked at all layers.conf files and check `LAYERSERIES_COMPAT_core  `, all of them are `"sumo thud warrior zeus dunfell gatesgarth"`

**Comment by Kottoz** [comment]
Edit the projectDir/layers/local/conf/layer.conf file to add dunfell, for example:

-------

LAYERSERIES_COMPAT_userspace-test = "warrior zeus dunfell gatesgarth"

-------

Save and rebuild.

**Comment by kraj** [comment]
hmm how did you. check the layers. It seems you are using master or gatesgrath release of meta-openembedded repo but dunfell for oe-core/poky, you should. be using same branch.

**Comment by Kottoz** [comment]
Thanks @kraj , i have switched to the same branch and it's worked.
i will close it.
