### ISSUE TITLE
Document beagleV bringup steps

### ISSUE THREAD

**Issue by kraj** [riscv/meta-riscv#280]
We need to document how to unfold beagleV step by step and build an image which can be booted on beagleV, perhaps starting from when one received the board shipment.

**Comment by pdp7** [comment]
I am trying to add resources here:
https://github.com/beagleboard/beaglev-starlight/blob/main/README.md

Please let me know what I can provide to help the documentation effort

@tpetazzoni buildroot branch has good details that might help oe/yocto:
https://github.com/tpetazzoni/buildroot/tree/beaglev

**Comment by kraj** [comment]
@pdp7 thanks thats a good start we probably can add a `beagleV.md` file on the topdir and start with steps.

**Comment by macpijan** [comment]
Added some basic readme to starti with in: https://github.com/riscv/meta-riscv/pull/279/files#diff-4a464ffb2af727f2accca11adf3ecbf92cfc51c0743ba66b144b091fcff9fc66

**Comment by kraj** [comment]
we now have merged initial support. Which includes documentation on bringing up beagleV as well.

**Comment by roemvaar** [comment]
I'm currently working on a tutorial for the BeagleV Starlight board bring up - If you want, I can make sure that this material gets merged into the docs.

**Comment by kraj** [comment]
soungs good @roemvaar

**Comment by pino-kim** [comment]
This Is not a proper site to ask about beagleV But.
beagleV is postponed or canceled?

**Comment by alistair23** [comment]
You will have to look at the BeagleV communiyt: https://forum.beagleboard.org/t/the-future-of-beaglev-community/30463

**Comment by pdp7** [comment]
@pino-kim feel free to either ask questions on my forum post that was linked above or through email: drew@beagleboard.org
