### ISSUE TITLE
how can i build yocto image without isa c

### ISSUE THREAD

**Issue by blackwatch997** [riscv/meta-riscv#298]
I want to build a Yocto image of rv64g, but I don’t know how to modify the "--march" and "--mabi" in the compilation parameters.

**Comment by kraj** [comment]
@blackwatch997 we control them globally see
https://git.openembedded.org/openembedded-core/tree/meta/conf/machine/include/riscv/arch-riscv.inc

**Comment by blackwatch997** [comment]
Great! It works!Thank  you!
