### ISSUE TITLE
prelink-native do_patch issue

### ISSUE THREAD

**Issue by pino-kim** [riscv/meta-riscv#32]
**Description**
I think it may be not our issue... but report it here at first.

ERROR: prelink-native-1.0+gitAUTOINC+a853a5d715-r0 do_patch: Command Error: 'quilt --quiltrc /home/pino/workspace/riscv-yocto/build/tmp-glibc/work/x86_64-linux/prelink-native/1.0+gitAUTOINC+a853a5d715-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-rtld-Add-missing-DT_NEEDED-DSOs-to-needed_list.patch
patching file ChangeLog
Hunk #1 FAILED at 1.
1 out of 1 hunk FAILED -- rejects in file ChangeLog
patching file src/rtld/rtld.c
Hunk #1 succeeded at 741 with fuzz 1 (offset 43 lines).
Hunk #2 succeeded at 888 with fuzz 2 (offset 45 lines).
Hunk #3 FAILED at 887.
1 out of 3 hunks FAILED -- rejects in file src/rtld/rtld.c
Patch 0001-rtld-Add-missing-DT_NEEDED-DSOs-to-needed_list.patch does not apply (enforce with -f)
ERROR: prelink-native-1.0+gitAUTOINC+a853a5d715-r0 do_patch: Function failed: patch_do_patch
ERROR: Logfile of failure stored in: /home/pino/workspace/riscv-yocto/build/tmp-glibc/work/x86_64-linux/prelink-native/1.0+gitAUTOINC+a853a5d715-r0/temp/log.do_patch.13980
ERROR: Task (virtual:native:/home/pino/workspace/riscv-yocto/openembedded-core/meta/recipes-devtools/prelink/prelink_git.bb:do_patch) failed with exit code '1'

[do_patch.txt](https://github.com/riscv/meta-riscv/files/2361614/do_patch.txt)

**Describe the results you received:**

**Describe the results you expected:**

**Comment by kraj** [comment]
https://github.com/riscv/meta-riscv/commit/3048b416520d3607bbe3909002175f952c40e1a4

should fix it
