### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by laoshaw** [riscv/meta-riscv#331]
please change:
repo init -u **git**://github.com/riscv/meta-riscv  -b master -m tools/manifests/riscv-yocto.xm
to:
repo init -u **https**://github.com/riscv/meta-riscv  -b master -m tools/manifests/riscv-yocto.xm

otherwise it can no longer to git cloned from github by default.

**Comment by kraj** [comment]
this is fixed with c1bc791e9fdb6fa480b4d141c5d4f5c0932923d2
