### ISSUE TITLE
What are all the supported Linux distributions can be used to work with meta-riscv project

### ISSUE THREAD

**Issue by billasurendra** [riscv/meta-riscv#343]
I am trying to build meta-riscv on Fedora 36 Linux distribution, and I am facing issues while building the image. I am doubtful wheather it is due to distribution  being used my me (Fedora 36). Please let me know what are all distributions does "meta-riscv yocto" support.

Thanks
Billa

**Comment by alistair23** [comment]
I haven't tested on Fedora 36 yet, but it should work. What error are you seeing?

**Comment by kraj** [comment]
always check https://git.yoctoproject.org/poky/tree/meta-poky/conf/distro/poky.conf#n35
for the release branch you are interested in.
