### ISSUE TITLE
Fetch error for starfive-tech u-boot

### ISSUE THREAD

**Issue by pratikfarkase94** [riscv/meta-riscv#355]
**Description**

**Describe the results you received:**

More info in the attached screenshots. 
![Screenshot from 2022-08-18 00-38-43](https://user-images.githubusercontent.com/37358512/185222811-6c367c0c-9416-4d62-a630-ed8c8c71e6a3.png)

**Comment by kraj** [comment]
@pratikfarkase94 describe your setup a little bit more. Secondly use latest master branch, here is what I did

```
% MACHINE=visionfive bitbake -e virtual/bootloader | grep SRCREV=
SRCREV="ccecef294d355e9d05edf0bb6058002a0fe08908"

```

which is different than what you reported

**Comment by pratikfarkase94** [comment]
SRCREV="ccecef294d355e9d05edf0bb6058002a0fe08908" as per "MACHINE=visionfive bitbake -e virtual/bootloader | grep SRCREV=SRCREV="ccecef294d355e9d05edf0bb6058002a0fe08908"" . 

Branch under use is master. Steps i followed : 

mkdir riscv-yocto && cd riscv-yocto
repo init -u https://github.com/riscv/meta-riscv  -b master -m tools/manifests/riscv-yocto.xml
repo sync
repo start work --all
. ./meta-riscv/setup.sh
MACHINE=beaglev-starlight-jh7100 bitbake core-image-weston

That's when i hit this error. I tried using a different internet connection but the issue seems to be same.

**Comment by kraj** [comment]
I see, so you are building for beagleV where I think the SRCREV might be stale and we have to upgrade that to something valid branch + srcrev but I think MACHINE=visionfive should work out fine. Can you try out this patch

https://github.com/riscv/meta-riscv/pull/356

and report back ?

**Comment by pratikfarkase94** [comment]
Works! Thanks. closing now.
