### ISSUE TITLE
linux-starfive-dev/5.19.0-rc4+ kernel compilation fails on beaglev master branch

### ISSUE THREAD

**Issue by pratikfarkase94** [riscv/meta-riscv#357]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**

**Comment by pratikfarkase94** [comment]
[kernel_compile_fail.txt](https://github.com/riscv/meta-riscv/files/9371369/kernel_compile_fail.txt)

**Comment by kraj** [comment]
try https://github.com/riscv/meta-riscv/pull/356/commits/d3754363b73482c2804442ba494bd71ccf90b2a5 and report back

**Comment by pratikfarkase94** [comment]
[kernel_compile_fail.txt](https://github.com/riscv/meta-riscv/files/9376179/kernel_compile_fail.txt)
more compilation errors.
