### ISSUE TITLE
u-boot-v.2021.04 fails to compile on beaglev master branch

### ISSUE THREAD

**Issue by pratikfarkase94** [riscv/meta-riscv#358]
[u-boot-fail.txt](https://github.com/riscv/meta-riscv/files/9376159/u-boot-fail.txt)

**Comment by pratikfarkase94** [comment]
Hi @kraj , This issue is still there on the latest master branch. However, i was able to go past the compilation error using this patch here : [https://lore.kernel.org/all/20221002172525.GD3044094@bill-the-cat/T/#Z2e.:..:20220128134713.2322800-1-alexandre.ghiti::40canonical.com:1arch:riscv:Makefile](url)

You can incorporate this patch in the u-boot sources and then close the issue.

**Comment by kraj** [comment]
should be fixed with above commit.
