### ISSUE TITLE
u-boot-v.2021.04 fails to compile on starfive master branch

### ISSUE THREAD

**Issue by zipotron** [riscv/meta-riscv#360]
![riscv](https://user-images.githubusercontent.com/6671137/187476317-cc8d0b51-cdc2-4e93-bb92-6e9261d31d9d.png)

**Comment by pratikfarkase94** [comment]
fixed here : [https://lore.kernel.org/all/20221002172525.GD3044094@bill-the-cat/T/#Z2e.:..:20220128134713.2322800-1-alexandre.ghiti::40canonical.com:1arch:riscv:Makefile](url)

**Comment by zipotron** [comment]
Thanks!
