### ISSUE TITLE
libxshmfence_1.3.bbappend shuld be renamed to libxshmfence_1.3%.bbappend

### ISSUE THREAD

**Issue by zhangze0722** [riscv/meta-riscv#375]
**Description**

zhangze@zhangze-virtual-machine:~/rvcore_yocto_new/build$ MACHINE=qemuriscv64 bitbake rvcore-image-full-cmdline
Loading cache: 100% |                                                                                                                                                                     | ETA:  --:--:--
Loaded 0 entries from dependency cache.
WARNING: /home/zhangze/rvcore_yocto_new/meta-cgl/meta-cgl-common/recipes-core/images/core-image-cgl-initramfs.bb: CGL compliance requires lsb, and meta-lsb is not included.               | ETA:  0:00:31
To disable this warning set LSB_WARN='0'
WARNING: /home/zhangze/rvcore_yocto_new/meta-cgl/meta-cgl-common/recipes-core/images/core-image-cgl.bb: CGL compliance requires lsb, and meta-lsb is not included.                         | ETA:  0:00:28
To disable this warning set LSB_WARN='0'
Parsing recipes: 100% |####################################################################################################################################################################| Time: 0:00:11
Parsing of 2976 .bb files complete (0 cached, 2976 parsed). 4573 targets, 216 skipped, 0 masked, 0 errors.
ERROR: No recipes in default available for:
  /home/zhangze/rvcore_yocto_new/meta-riscv/recipes-graphics/xorg-lib/libxshmfence_1.3.bbappend

Summary: There were 2 WARNING messages.
Summary: There was 1 ERROR message, returning a non-zero exit code.

meta-riscv/recipes-graphics/xorg-lib/libxshmfence_1.3.bbappend
shuld be 
meta-riscv/recipes-graphics/xorg-lib/libxshmfence_1.3%.bbappend

**Comment by kraj** [comment]
should be fixed with https://github.com/riscv/meta-riscv/pull/373
