### ISSUE TITLE
Why not use poky？

### ISSUE THREAD

**Issue by zhang-wenchao** [riscv/meta-riscv#390]
As this project uses oe-core and bitbake, there are differences when using it with other layers. Can I ask why this design and whether I can use poky instead of oe-core + bitbake.

**Comment by kraj** [comment]
yes you can very well use poky, since poky and oe-core metadata is same these days.  perhaps we should setup another template for setup to us it.

**Comment by zhang-wenchao** [comment]
Another question is why bitbake master is needed, this dependency seems redundant to me. The project should only rely on oe-core or poky.
