### ISSUE TITLE
current go-cross cannot support cgo for riscv64

### ISSUE THREAD

**Issue by zhangze0722** [riscv/meta-riscv#394]
**Description**

current go-cross cannot support cgo for riscv64, should use this branch
https://github.com/4a6f656c/go.git
https://github.com/golang/go/issues/36641

**Steps to reproduce the issue:**
1. compile runc with seccomp support, go can not use cgo compile c code
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional details (revisions used, host distro, etc.):**

**Comment by kraj** [comment]
it should be fixed in upstream go compiler these days - https://github.com/golang/go/issues/36641
