### ISSUE TITLE
go_1.19.4.bb not install standard lib code

### ISSUE THREAD

**Issue by zhangze0722** [riscv/meta-riscv#395]
**Description**
compiling almost any go project need standard lib source in GOROOT/src,
but /usr/lib/go/src/ is empty

**Steps to reproduce the issue:**
1.git clone https://github.com/opencontainers/runc   in qemuriscv64
2.exec make  will build go source code, this step need go standard lib source code
3.

**Describe the results you received:**
build faild, can not find go standard lib

**Describe the results you expected:**
get runc execuable

**Additional information you deem important (e.g. issue happens only occasionally):**

this is an upstream issue, poky's go recipese is the same,
go  project need all the source code before compiler can compile it.

**Additional details (revisions used, host distro, etc.):**

If I copied the src and pkg/include from go git source into qemuriscv64/usr/lib/go/
then build is ok.

**Comment by kraj** [comment]
I think you need to install full go SDK into image as it seems you are building on the qemu running yocto generated image
something like below in `local.conf`
```
IMAGE_INSTALL:append = " packagegroup-go-sdk-target"
```
