### ISSUE TITLE
Where is recipes-bsp/boot0/boot0.bb?

### ISSUE THREAD

**Issue by nobody93** [riscv/meta-riscv#401]
According to https://www.youtube.com/watch?v=QdBG6HUeE6w, there is boot0 in recipes-bsp/boot0/boot0.bb, but I could not find it. What could I be missing here?

Thank you.

Kind regards,

jh

**Comment by kraj** [comment]
It was obsolete and removed with 05a629193aea67a4391aa7ae3f236cc6fa9208f7

**Comment by cordlandwehr** [comment]
@nobody93 the currently best source of information about the Allwinner D1 Nezha boot process is here https://linux-sunxi.org/Allwinner_Nezha ; together with a few information what changed around boot0

**Comment by kraj** [comment]
closing, please re-open if needed.
