### ISSUE TITLE
build report #40

### ISSUE THREAD

**Issue by pino-kim** [riscv/meta-riscv#41]
Dear @kraj.
Is not a issue but repot build report PR #40 
I kerenl fetch well and bootup well by qemu
I build it ubuntu 16.04 cli interface.  

## sysroot buildlog
[log_do_rootfs_kernel_4_15_20181005.txt](https://github.com/riscv/meta-riscv/files/2450894/log_do_rootfs_kernel_4_15_20181005.txt)
[log_do_rootfs_kernel_4_18_20181005.txt](https://github.com/riscv/meta-riscv/files/2450899/log_do_rootfs_kernel_4_18_20181005.txt)

## runqemu result(riscv-linux 4.15 bb)
![4_15_riscv_runqemu_boot_20181005](https://user-images.githubusercontent.com/29390119/46544299-328ab680-c8fe-11e8-90c0-a1952d9c5455.JPG)

## runqemu result(riscv-linux 4.18 bb)
![4_18_riscv_runqemu_boot_20181005](https://user-images.githubusercontent.com/29390119/46544340-50f0b200-c8fe-11e8-863b-71e0098892ba.JPG)

**Comment by kraj** [comment]
this can be closed now. Please reopen if needed
