### ISSUE TITLE
Question about core-image-sato

### ISSUE THREAD

**Issue by pino-kim** [riscv/meta-riscv#51]
**Description**
I builded core-image-sato and no compile issue.
But I ran it command.

```$ runqemu```

The console has stucked after executing the command.
Anyone have some idea where to find solution?????
Nothing happen my qemu. So I can't find where to start first.
first I want to run it not a console, seperate screen.
I attach qemu command too.
thanks. 

**Steps to reproduce the issue:**
1. $ bitbake core-image-sato
2. $ runqemu

**Describe the results you received:**
stucked console, but can exit it Ctrl+C.

**Describe the results you expected:**
launch core-image-sato. All is fine.

**Additional information you deem important (e.g. issue happens only occasionally):**
## runqemu command :
```/home/pino/workspace/opensource/riscv-yocto/build/tmp-glibc/work/x86_64-linux/qemu-helper-native/1.0-r1/recipe-sysroot-native/usr/bin/qemu-system-riscv64 -device virtio-net-device,netdev=net0,mac=52:54:00:12:34:02 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -drive id=disk0,file=/home/pino/workspace/opensource/riscv-yocto/build/tmp-glibc/deploy/images/qemuriscv64/core-image-sato-qemuriscv64-20181126112726.rootfs.ext4,if=none,format=raw -device virtio-blk-device,drive=disk0 -show-cursor -monitor null  -machine virt  -m 512 -serial mon:vc -serial null -kernel /home/pino/workspace/opensource/riscv-yocto/build/tmp-glibc/deploy/images/qemuriscv64/bbl -append 'root=/dev/vda rw highres=off  mem=512M ip=192.168.7.2::192.168.7.1:255.255.255.0 console=ttyAMA0,115200 console=tty '```

**Additional details (revisions used, host distro, etc.):**
## build infor
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.40.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "ubuntu-16.04"
TARGET_SYS           = "riscv64-oe-linux"
MACHINE              = "qemuriscv64"
DISTRO               = "nodistro"
DISTRO_VERSION       = "nodistro.0"
TUNE_FEATURES        = "riscv64 littleendian"
meta                 = "work:04469ab5b7f0446404b4cb55a15595678581ab26"
meta-oe      
meta-multimedia      
meta-python      
meta-networking      = "work:c26b10b155cf7873ffc8e966f95fd4abed8230c6"
meta-riscv           = "work:4f4e1753d416f942f58d62340bec5f8b447e9e41"

## Console image(stucked)
![image](https://user-images.githubusercontent.com/29390119/49054501-c6f70280-f237-11e8-84e4-bd7a1ff82493.png)

**Comment by kraj** [comment]
Can you try

```
runqemu nographic
```

**Comment by pino-kim** [comment]
Hi @kraj 

Thanks to reply

If  command ```runqemu nographic``` It boot up CLI mode.
But am I right core-image-sato is GUI mode.
here is boot up pic
![image](https://user-images.githubusercontent.com/29390119/49063957-8cec2780-f25c-11e8-951a-67d5289c7c9a.png)

**Comment by kraj** [comment]
GUI does not work yet

**Comment by alistair23** [comment]
The next version of QEMU after the on currently in RC (3.2) should support displays for RISC-V.

**Comment by palmer-dabbelt** [comment]
Just to be clear: QEMU 3.1 is in RCs right now and is scheduled to release in a few weeks.  There are patches to enable PCI express queued for QEMU 3.2, which will release in a few months.

**Comment by kraj** [comment]
qemu 3.1 has been added to OE-core now.

**Comment by alistair23** [comment]
PCIe support isn't in 3.1, it should make it into QEMU 3.2.

**Comment by kraj** [comment]
yes I  know :)  I know :)

**Comment by alistair23** [comment]
QEMU 4.0 has been merged into OE. GUI should work for you now.

**Comment by kraj** [comment]
> QEMU 4.0 has been merged into OE. GUI should work for you now.

closing
