### ISSUE TITLE
compile error with meta-riscv

### ISSUE THREAD

**Issue by 13824125580** [riscv/meta-riscv#92]
thanks , i got the error output with command  MACHINE=freedom-u540 wic create freedom-u540-bbl -e core-image-minimal command, so how to dealwith this?

Initialising tasks: 100% |######################################################################################################################################################| Time: 0:00:00
Sstate summary: Wanted 0 Found 0 Missed 0 Current 46 (0% match, 100% complete)
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Tasks Summary: Attempted 357 tasks of which 357 didn't need to be rerun and all succeeded.
NOTE: Writing buildhistory
INFO: Build artifacts not found, exiting.
INFO:   (Please check that the build artifacts for the machine
INFO:    selected in local.conf actually exist and that they
INFO:    are the correct artifacts for the image (.wks file)).

ERROR: ("The artifact that couldn't be found was %s:\n  %s", 'rootfs-dir', '/home/czl/WorkSpace/sifive/riscv-yocto/build/tmp-glibc/work/qemuriscv64-oe-linux/core-image-minimal/1.0-r0/rootfs')

**Comment by kraj** [comment]
wic image should be generated automatically for `MACHINE = "freedom-u540"`

**Comment by kraj** [comment]
you might want to use Yoe Distro which support RISC-V https://github.com/YoeDistro/yoe-distro

**Comment by kraj** [comment]
is this still an issue with latest master ?

**Comment by kraj** [comment]
closing due to lack of response
